language: node_js
branches:
  only:
    - master
node_js:
   - "0.11.11"
   - "0.11.10"
   - "0.10.25"
   - "0.10.24"
   - "0.10.23"
   - "0.10.22"
   - "0.10.20"
   - "0.10.15"
   - "0.10.14"
   - "0.10.13"
   - "0.10.10"